<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 require APPPATH . '/libraries/BaseController.php'; 
class Contact extends BaseController{
    function __construct()
    {
        parent::__construct(); 
    } 

    
    function index()
    {
    
      $data['_view'] = 'contact';
      $this->global['pageTitle'] = 'eVideoPlus : Contact';
       $this->load->view('contact',$data);
    }

    function sendContactUsDetails()
    {
    
      $status = '';
        
        $this->load->library('form_validation');
        
        $this->form_validation->set_rules('name','text','required');
        $this->form_validation->set_rules('email','Email','trim|required|valid_email');
        $this->form_validation->set_rules('subject','text','required');
        $this->form_validation->set_rules('message','text','required');
                
        if($this->form_validation->run() == FALSE)
        {
            setFlashData($status, "Form validation failed");
            $this->contact();
        }
        else 

        { 

        
         $data['name'] = $this->input->post('name');
         $data['email'] = $this->input->post('email');
         $data['subject'] = $this->input->post('subject');
         $data['message'] =$this->input->post('message');
         
           
          $sendStatus = sendContactUsDetails($data);

                    if($sendStatus){
                        $status = "send";
                        setFlashData($status, "We received your message.");
                    } 
                }
              redirect('/contact');
         
  }
}
