<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
require APPPATH . '/libraries/BaseController.php';
class Video extends BaseController{ 
    function __construct()
    {
        parent::__construct();
        $this->isLoggedIn();   
        $this->load->model('Video_model');
    } 

    /*
     * Listing of video
     */
    function index()
    {
        $data['video'] = $this->Video_model->get_all_video();
        foreach($data['video'] as $v){
            $this->load->model('Category_model');
            $data['category'] = $this->Category_model->get_category($v['cat_id']);

            $this->load->model('Technology_model');
            $data['technology'] = $this->Technology_model->get_technology($v['tech_id']);
        }
        $this->global['pageTitle'] = 'eVideoPlus : Videos';
        $this->loadViews("video/index", $this->global, $data, NULL);    }

    /*
     * Adding a new video
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('video_url','Video Url','required|max_length[3000]');
		$this->form_validation->set_rules('tech_id','Tech Id','required');
		$this->form_validation->set_rules('cat_id','Cat Id','required');
		$this->form_validation->set_rules('title','Title','max_length[3000]');
		
		if($this->form_validation->run())     
        {   $today = date("m/d/Y h:i:s a");
            $params = array(
                    'cat_id' => $this->input->post('cat_id'),
                    'tech_id' => $this->input->post('tech_id'),
                    'title' => $this->input->post('title'),
                    'video_url' => $this->input->post('video_url'),
                    'description' => $this->input->post('description'),
                    'date' => $today,
                    'addedBy' => $this->global['name'],
            );
            
            $video_id = $this->Video_model->add_video($params);
            redirect('video/index');
        }
        else
        {
			$this->load->model('Category_model');
			$data['all_category'] = $this->Category_model->get_all_category();

			$this->load->model('Technology_model');
			$data['all_technology'] = $this->Technology_model->get_all_technology();
            
            $data['_view'] = 'video/add';
            $this->global['pageTitle'] = 'eVideoPlus : Videos';
            
            $this->loadViews("video/add", $this->global, $data, NULL);
        }
    }  

    /*
     * Editing a video
     */
    function edit($video_id)
    {   
        // check if the video exists before trying to edit it
        $data['video'] = $this->Video_model->get_video($video_id);
        
        if(isset($data['video']['video_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('video_url','Video Url','required|max_length[3000]');
			$this->form_validation->set_rules('tech_id','Tech Id','required');
			$this->form_validation->set_rules('cat_id','Cat Id','required');
			$this->form_validation->set_rules('title','Title','max_length[3000]');
		
			if($this->form_validation->run())     
            {   $today = date("m/d/Y h:i:s a");
                $params = array(
					'cat_id' => $this->input->post('cat_id'),
					'tech_id' => $this->input->post('tech_id'),
					'title' => $this->input->post('title'),
					'video_url' => $this->input->post('video_url'),
                    'description' => $this->input->post('description'),
                    'date' => $today,
                    'addedBy' => $this->global['name'],
                );

                $this->Video_model->update_video($video_id,$params);            
                redirect('video/index');
            }
            else
            {
				$this->load->model('Category_model');
				$data['all_category'] = $this->Category_model->get_all_category();

				$this->load->model('Technology_model');
				$data['all_technology'] = $this->Technology_model->get_all_technology();

                $data['_view'] = 'video/edit';
                $this->global['pageTitle'] = 'eVideoPlus : Edit Video';
            
                $this->loadViews("video/edit", $this->global, $data, NULL);
            }
        }
        else
            show_error('The video you are trying to edit does not exist.');
    } 

    /*
     * Deleting video
     */
    function remove($video_id)
    {
        $video = $this->Video_model->get_video($video_id);

        // check if the video exists before trying to delete it
        if(isset($video['video_id']))
        {
            $this->Video_model->delete_video($video_id);
            redirect('video/index');
        }
        else
            show_error('The video you are trying to delete does not exist.');
    }
    
}
